import Navbar from "./Navbar"

export const metadata = {
  title: "ซ้งศรีเจริญ",
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <Navbar />
      {children}
    </>
  )
}
